title: "Walks"
description: "walkingbot's log of city walks"
url: "https://walkingbot.github.io"   # GitHub Pages user/organization site
baseurl: "/walks"                    # Project site path
theme: minima
plugins:
  - jekyll-feed
